-- Safe cancellation and FIFO allocation audit for outgoing inventory.
-- Run once in Supabase SQL Editor after migrations 001, 002 and 003.

ALTER TABLE public.transaksi_keluar
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'AKTIF',
  ADD COLUMN IF NOT EXISTS dibatalkan_pada timestamptz NULL,
  ADD COLUMN IF NOT EXISTS dibatalkan_oleh uuid NULL;

ALTER TABLE public.transaksi_keluar
  DROP CONSTRAINT IF EXISTS transaksi_keluar_status_check;

ALTER TABLE public.transaksi_keluar
  ADD CONSTRAINT transaksi_keluar_status_check
  CHECK (status IN ('AKTIF','DIBATALKAN'));

CREATE TABLE IF NOT EXISTS public.transaksi_kuasi_alokasi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaksi_keluar_id integer NOT NULL REFERENCES public.transaksi_keluar(id) ON DELETE RESTRICT,
  detail_barang_keluar_id integer NOT NULL REFERENCES public.detail_barang_keluar(id) ON DELETE RESTRICT,
  stok_kuasi_id integer NOT NULL REFERENCES public.stok_kuasi(id) ON DELETE RESTRICT,
  jumlah integer NOT NULL CHECK (jumlah > 0),
  digit_awal integer NOT NULL,
  digit_akhir integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT transaksi_kuasi_alokasi_range_check CHECK (digit_akhir >= digit_awal),
  CONSTRAINT transaksi_kuasi_alokasi_detail_unique UNIQUE (detail_barang_keluar_id)
);

CREATE INDEX IF NOT EXISTS idx_kuasi_alokasi_tx
  ON public.transaksi_kuasi_alokasi(transaksi_keluar_id);

CREATE INDEX IF NOT EXISTS idx_kuasi_alokasi_batch
  ON public.transaksi_kuasi_alokasi(stok_kuasi_id);

CREATE OR REPLACE FUNCTION public.record_barang_keluar(
  p_tanggal date, p_penyerah_nama text, p_penyerah_jabatan text, p_penyerah_nip text,
  p_penerima_nama text, p_penerima_jabatan text, p_penerima_nip text,
  p_tujuan_ruangan text, p_jenis_dokumen text, p_items jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tx_id integer;
  v_detail_id integer;
  v_item jsonb;
  v_barang_id integer;
  v_jumlah integer;
  v_total integer;
  v_stock integer;
  v_kategori text;
  v_batch record;
  v_take integer;
  v_start integer;
  v_end integer;
  v_prefix text;
  v_pad integer;
  v_awal text;
  v_akhir text;
  v_dus text;
BEGIN
  IF NOT public.sipb_is_active_user() THEN
    RAISE EXCEPTION 'Akun SIPB tidak aktif';
  END IF;

  IF p_tanggal IS NULL THEN
    RAISE EXCEPTION 'Tanggal transaksi wajib diisi';
  END IF;

  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Minimal satu barang harus dipilih';
  END IF;

  FOR v_barang_id, v_total IN
    SELECT (x->>'barang_id')::integer, SUM((x->>'jumlah')::integer)
    FROM jsonb_array_elements(p_items) x
    GROUP BY (x->>'barang_id')::integer
  LOOP
    IF v_total < 1 THEN
      RAISE EXCEPTION 'Jumlah harus positif';
    END IF;

    SELECT sisa, kategori
      INTO v_stock, v_kategori
    FROM public.barang
    WHERE id = v_barang_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Barang ID % tidak ditemukan', v_barang_id;
    END IF;

    IF v_total > COALESCE(v_stock, 0) THEN
      RAISE EXCEPTION 'Stok barang ID % tidak mencukupi. Sisa %, diminta %',
        v_barang_id, COALESCE(v_stock, 0), v_total;
    END IF;

    IF lower(COALESCE(v_kategori, '')) = 'kuasi' THEN
      IF (
        SELECT COALESCE(SUM(sisa_lembar), 0)
        FROM public.stok_kuasi
        WHERE barang_id = v_barang_id AND sisa_lembar > 0
      ) < v_total THEN
        RAISE EXCEPTION 'Batch Kuasi untuk barang ID % tidak mencukupi', v_barang_id;
      END IF;
    END IF;
  END LOOP;

  INSERT INTO public.transaksi_keluar
    (tanggal_keluar, penyerah_nama, penyerah_jabatan, penyerah_nip,
     penerima_nama, penerima_jabatan, penerima_nip, tujuan_ruangan, jenis_dokumen, status)
  VALUES
    (p_tanggal, p_penyerah_nama, p_penyerah_jabatan, p_penyerah_nip,
     p_penerima_nama, p_penerima_jabatan, p_penerima_nip,
     p_tujuan_ruangan, COALESCE(p_jenis_dokumen, 'Nota Dinas'), 'AKTIF')
  RETURNING id INTO v_tx_id;

  FOR v_barang_id, v_total IN
    SELECT (x->>'barang_id')::integer, SUM((x->>'jumlah')::integer)
    FROM jsonb_array_elements(p_items) x
    GROUP BY (x->>'barang_id')::integer
  LOOP
    SELECT kategori
      INTO v_kategori
    FROM public.barang
    WHERE id = v_barang_id
    FOR UPDATE;

    IF lower(COALESCE(v_kategori, '')) = 'kuasi' THEN
      FOR v_batch IN
        SELECT *
        FROM public.stok_kuasi
        WHERE barang_id = v_barang_id AND sisa_lembar > 0
        ORDER BY tanggal_masuk, id
        FOR UPDATE
      LOOP
        EXIT WHEN v_total <= 0;

        v_take := LEAST(v_total, v_batch.sisa_lembar);
        v_start := v_batch.digit_sekarang;
        v_end := v_start + v_take - 1;
        v_prefix := COALESCE(v_batch.prefix_huruf, '');
        v_pad := COALESCE(v_batch.panjang_digit, 0);
        v_awal := v_prefix || lpad(v_start::text, v_pad, '0');
        v_akhir := v_prefix || lpad(v_end::text, v_pad, '0');
        v_dus := v_batch.nomor_dus;

        INSERT INTO public.detail_barang_keluar
          (transaksi_keluar_id, barang_id, jumlah, nomor_awal, nomor_akhir, nomor_dus)
        VALUES
          (v_tx_id, v_barang_id, v_take, v_awal, v_akhir, v_dus)
        RETURNING id INTO v_detail_id;

        INSERT INTO public.transaksi_kuasi_alokasi
          (transaksi_keluar_id, detail_barang_keluar_id, stok_kuasi_id,
           jumlah, digit_awal, digit_akhir)
        VALUES
          (v_tx_id, v_detail_id, v_batch.id, v_take, v_start, v_end);

        UPDATE public.stok_kuasi
        SET digit_sekarang = v_end + 1,
            sisa_lembar = sisa_lembar - v_take
        WHERE id = v_batch.id;

        v_total := v_total - v_take;
      END LOOP;
    ELSE
      INSERT INTO public.detail_barang_keluar
        (transaksi_keluar_id, barang_id, jumlah)
      VALUES
        (v_tx_id, v_barang_id, v_total);
      v_total := 0;
    END IF;

    IF v_total > 0 THEN
      RAISE EXCEPTION 'Stok Kuasi tidak mencukupi';
    END IF;
  END LOOP;

  UPDATE public.barang b
  SET terpakai = COALESCE(b.terpakai, 0) + x.jumlah,
      sisa = COALESCE(b.sisa, 0) - x.jumlah
  FROM (
    SELECT (j->>'barang_id')::integer AS id,
           SUM((j->>'jumlah')::integer) AS jumlah
    FROM jsonb_array_elements(p_items) j
    GROUP BY (j->>'barang_id')::integer
  ) x
  WHERE b.id = x.id;

  RETURN jsonb_build_object('id', v_tx_id, 'status', 'success');
END;
$$;

REVOKE ALL ON FUNCTION public.record_barang_keluar(date,text,text,text,text,text,text,text,text,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.record_barang_keluar(date,text,text,text,text,text,text,text,text,jsonb) TO authenticated;

CREATE OR REPLACE FUNCTION public.cancel_barang_keluar(p_transaksi_id integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_tx record;
  v_role text;
  v_detail record;
  v_batch_id integer;
  v_consumed integer;
  v_batch_total integer;
  v_has_untracked_kuasi boolean;
BEGIN
  IF NOT public.sipb_is_active_user() THEN
    RAISE EXCEPTION 'Akun SIPB tidak aktif';
  END IF;

  SELECT role
    INTO v_role
  FROM public.user_profiles
  WHERE id = auth.uid() AND is_active = true;

  IF COALESCE(lower(v_role), '') <> 'admin' THEN
    RAISE EXCEPTION 'Hanya admin yang dapat membatalkan transaksi barang keluar';
  END IF;

  SELECT *
    INTO v_tx
  FROM public.transaksi_keluar
  WHERE id = p_transaksi_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaksi barang keluar #% tidak ditemukan', p_transaksi_id;
  END IF;

  IF COALESCE(v_tx.status, 'AKTIF') <> 'AKTIF' THEN
    RAISE EXCEPTION 'Transaksi #% sudah dibatalkan', p_transaksi_id;
  END IF;

  SELECT EXISTS (
    SELECT 1
    FROM public.detail_barang_keluar d
    JOIN public.barang b ON b.id = d.barang_id
    WHERE d.transaksi_keluar_id = p_transaksi_id
      AND lower(COALESCE(b.kategori, '')) = 'kuasi'
      AND NOT EXISTS (
        SELECT 1
        FROM public.transaksi_kuasi_alokasi a
        WHERE a.detail_barang_keluar_id = d.id
      )
  )
  INTO v_has_untracked_kuasi;

  IF v_has_untracked_kuasi THEN
    RAISE EXCEPTION
      'Transaksi #% memakai barang Kuasi dari transaksi lama yang belum memiliki audit batch. Transaksi ini tidak dapat dibatalkan otomatis.',
      p_transaksi_id;
  END IF;

  -- Lock affected barang first, matching the lock order used by record_barang_keluar.
  -- This keeps concurrent outgoing/cancellation operations from taking locks in opposite order.
  FOR v_detail IN
    SELECT DISTINCT barang_id
    FROM public.detail_barang_keluar
    WHERE transaksi_keluar_id = p_transaksi_id
    ORDER BY barang_id
  LOOP
    PERFORM 1
    FROM public.barang
    WHERE id = v_detail.barang_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Barang ID % tidak ditemukan saat pembatalan', v_detail.barang_id;
    END IF;
  END LOOP;

  -- Lock all affected Kuasi batch rows before changing the transaction status.
  FOR v_batch_id IN
    SELECT DISTINCT a.stok_kuasi_id
    FROM public.transaksi_kuasi_alokasi a
    WHERE a.transaksi_keluar_id = p_transaksi_id
    ORDER BY a.stok_kuasi_id
  LOOP
    PERFORM 1
    FROM public.stok_kuasi
    WHERE id = v_batch_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Batch Kuasi #% tidak ditemukan', v_batch_id;
    END IF;
  END LOOP;

  UPDATE public.transaksi_keluar
  SET status = 'DIBATALKAN',
      dibatalkan_pada = now(),
      dibatalkan_oleh = auth.uid()
  WHERE id = p_transaksi_id;

  -- Restore ordinary inventory quantities.
  FOR v_detail IN
    SELECT barang_id, SUM(jumlah)::integer AS jumlah
    FROM public.detail_barang_keluar
    WHERE transaksi_keluar_id = p_transaksi_id
    GROUP BY barang_id
  LOOP
    UPDATE public.barang
    SET sisa = COALESCE(sisa, 0) + v_detail.jumlah,
        terpakai = GREATEST(0, COALESCE(terpakai, 0) - v_detail.jumlah)
    WHERE id = v_detail.barang_id;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Barang ID % tidak ditemukan saat pembatalan', v_detail.barang_id;
    END IF;
  END LOOP;

  -- Rebuild each affected Kuasi batch from the allocation ledger.
  -- This is safer than simply subtracting the canceled quantity because
  -- later transactions may already have consumed the same batch.
  FOR v_batch_id IN
    SELECT DISTINCT a.stok_kuasi_id
    FROM public.transaksi_kuasi_alokasi a
    WHERE a.transaksi_keluar_id = p_transaksi_id
    ORDER BY a.stok_kuasi_id
  LOOP
    SELECT (digit_akhir - digit_awal + 1)
      INTO v_batch_total
    FROM public.stok_kuasi
    WHERE id = v_batch_id
    FOR UPDATE;

    SELECT COALESCE(SUM(a.jumlah), 0)::integer
      INTO v_consumed
    FROM public.transaksi_kuasi_alokasi a
    JOIN public.transaksi_keluar t ON t.id = a.transaksi_keluar_id
    WHERE a.stok_kuasi_id = v_batch_id
      AND COALESCE(t.status, 'AKTIF') = 'AKTIF';

    UPDATE public.stok_kuasi
    SET digit_sekarang = digit_awal + v_consumed,
        sisa_lembar = v_batch_total - v_consumed
    WHERE id = v_batch_id;
  END LOOP;

  RETURN jsonb_build_object(
    'id', p_transaksi_id,
    'status', 'cancelled'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.cancel_barang_keluar(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cancel_barang_keluar(integer) TO authenticated;

REVOKE ALL ON FUNCTION public.sipb_is_active_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.sipb_is_active_user() TO authenticated;
